### ISSUE TITLE
請問有支持 Mac 的計劃嗎？

### ISSUE THREAD

**Issue by qoli** [esozh/eso_zh_ui#1]
RT.
感謝。 #

**Comment by bssthu** [comment]
应该是支持的，只是手上没有Mac，没测试过。安装到Mac的插件目录里就行。
如果报错，可以试试暂时删除其他插件。

**Comment by qoli** [comment]
以參考的辦法。
啟動後 **Language** 依然為 **zh**。

右下角已經是中國圖標。

但是漢化在那裡？

<img width="2560" alt="2016-09-12 10 48 14" src="https://cloud.githubusercontent.com/assets/2818670/18423305/785c2d8a-78d6-11e6-9525-53ddca09011d.png">

**Comment by bssthu** [comment]
启动的时候有没有从启动器进？如果从启动器打开，启动器会覆盖语言的设置。

你可以试试启动 `~/Applications/Zenimax Online/The Elder Scrolls Online/game_mac/pubplayerclient/eso` 或者
`~/Applications/Zenimax Online/The Elder Scrolls Online/game_mac/pubplayerclient/eso64`

**Comment by qoli** [comment]
我说了。

> 以參考的辦法。
> 啟動後 Language 依然為 zh。

就是直接啟動 eso，沒有經過啟動器。

**Comment by bssthu** [comment]
如果把 `esoui` 文件夹重命名成 `EsoUI` 呢？

**Comment by shuryanc** [comment]
试了，在Mac下是可行的
根据教学安装后进游戏再按国旗，自动从新载入后会变成中文介面
如果仍然不行，试试把UserSetting.txt改成锁定然后再执行游戏

图证（稍微繁化了一下）：
![screenshot](https://cloud.githubusercontent.com/assets/13993374/18561124/1f43df1c-7bb1-11e6-85a0-731a3df7cdb6.png)
